New resource and various bug fixes
dsccommunity/SharePointDsc pull request #1406
Opened 2022-05-10 06:52 UTC by ykuijs

#### Pull Request (PR) description

This PR adds the SPSearchCrawlDatabase resource, adds extra troubleshooting information, implements export logic for SPShellAdmin, increases export requirement to ReverseDsc v2.0.0.11 and fixes several bugs.

#### This Pull Request (PR) fixes the following issues

- Fixes #493 
- Fixes #1404 
- Fixes #1389 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2022-05-10 06:53 UTC, ykuijs commented
@NikCharlebois Up for a review?

2022-05-10 13:10 UTC, NikCharlebois requested changes
Need to update some of the descriptions.

2022-05-10 13:10 UTC, NikCharlebois commented on SharePointDsc/DSCResources/MSFT_SPSearchCrawlDatabase/MSFT_SPSearchCrawlDatabase.schema.mof
> +    [Write, Description("Present if the service app should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
In this case it doesn't deal with the Service App, but rather with the crawl db. We should update the definition

2022-05-11 21:05 UTC, NikCharlebois approved these changes
LGTM

2022-05-12 07:01 UTC, merged